[package]
name = "lance_bridge"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"

[lib]
crate-type = ["staticlib"]

[dependencies]
arrow-array = { version = "58", features = ["ffi"] }
arrow-data = "58"
arrow-schema = { version = "58", features = ["ffi"] }
lance = { path = "../../lance/rust/lance" }
tokio = { version = "1", features = ["rt", "sync"] }
