[package]
name = "lance_bridge"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"

[lib]
crate-type = ["staticlib"]

[dependencies]
arrow-array = "57.0.0"
arrow-data = "57.0.0"
arrow-schema = "57.0.0"
lance = { path = "../../lance/rust/lance" }
tokio = { version = "1", features = ["rt", "sync"] }
