# Arrow expects find_package(Snappy) when Snappy_SOURCE=SYSTEM; this maps our
# in-tree snappy target to the conventional Snappy::snappy(-static) names.
if(TARGET Snappy::snappy-static)
  set(Snappy_FOUND TRUE)
  set(Snappy_VERSION "1.1.10")
  set(Snappy_TARGET Snappy::snappy-static)
elseif(TARGET Snappy::snappy)
  set(Snappy_FOUND TRUE)
  set(Snappy_VERSION "1.1.10")
  set(Snappy_TARGET Snappy::snappy)
endif()

if(Snappy_FOUND)
  set(Snappy_LIBRARIES ${Snappy_TARGET})
  get_target_property(Snappy_INCLUDE_DIRS ${Snappy_TARGET} INTERFACE_INCLUDE_DIRECTORIES)
  if(Snappy_INCLUDE_DIRS)
    list(GET Snappy_INCLUDE_DIRS 0 Snappy_INCLUDE_DIR)
  endif()
  set(Snappy_LIB ${Snappy_TARGET})
  if(NOT SNAPPY_TARGET)
    set(SNAPPY_TARGET ${Snappy_TARGET})
  endif()
else()
  message(STATUS "Snappy target not found in-tree")
endif()
