if(TARGET Snappy::snappy-static)
  set(Snappy_FOUND TRUE)
  set(Snappy_VERSION "1.1.10")
  set(Snappy_TARGET Snappy::snappy-static)
elseif(TARGET Snappy::snappy)
  set(Snappy_FOUND TRUE)
  set(Snappy_VERSION "1.1.10")
  set(Snappy_TARGET Snappy::snappy)
endif()

if(Snappy_FOUND)
  set(Snappy_LIBRARIES ${Snappy_TARGET})
  get_target_property(Snappy_INCLUDE_DIRS ${Snappy_TARGET} INTERFACE_INCLUDE_DIRECTORIES)
  if(NOT SNAPPY_TARGET)
    set(SNAPPY_TARGET ${Snappy_TARGET})
  endif()
else()
  message(STATUS "Snappy target not found")
endif()
